import { useRef, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, ChevronRight, CircleHelp, CloudUpload, FileCode2, FolderKanban, GitBranch, Play, Radar, Search, Settings2, Sparkles, TerminalSquare, UploadCloud, Workflow } from "lucide-react";
import { AgentRegistry, EvaluationWorkspace, ExecutionHistory } from "./WorkspaceModules";

type Props = { onBack: () => void; onAnalyze: (trace: string) => void };
type WorkspaceView = "overview" | "agents" | "executions" | "rca" | "evaluations" | "deployments";

const nav = [
  ["Overview", "overview", Radar], ["Agents", "agents", FolderKanban], ["Executions", "executions", GitBranch], ["RCA & evidence", "rca", Sparkles], ["Evaluations", "evaluations", CheckCircle2], ["Deployments", "deployments", Workflow],
] as const;

const starters = [
  { label: "OpenTelemetry", value: '{"resourceSpans":[{"scopeSpans":[{"spans":[{"name":"agent.run","status":{"code":2}}]}]}]}' },
  { label: "LangSmith", value: "run_id: run_8F3A2D\nname: planner\nstatus: error\nerror: retrieval returned an invalid quarter" },
  { label: "Plain text", value: "[14:32:08] planner -> retrieval\n[14:32:09] sql_query returned Q3 for requested Q4\n[14:32:10] reviewer: failed" },
];

function Overview({ onAnalyze }: { onAnalyze: (trace: string) => void }) {
  const [trace, setTrace] = useState("");
  const [format, setFormat] = useState("AUTO");
  const [error, setError] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);
  const analyze = () => { if (!trace.trim()) { setError("Paste a trace or choose a starter to begin the investigation."); return; } setError(""); onAnalyze(trace); };
  const pickFile = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => setTrace(String(reader.result || "")); reader.readAsText(file); };
  return <>
    <div className="workspace-page-head"><div><span className="workspace-eyebrow"><i /> Agent engineering workspace</span><h1>Make every run explainable.</h1><p>Bring in a trace, find the decisive step, and turn the diagnosis into the next engineering move.</p></div><span className="workspace-overview-note"><span className="status-live" /> Private workspace ready</span></div>
    <section className="trace-intake"><div className="trace-intake-head"><div><span className="workspace-eyebrow">START AN INVESTIGATION</span><h2>What happened in the run?</h2><p>Paste any agent trace. 404 AI normalizes the run, builds the execution graph, and surfaces the earliest causal break.</p></div><div className="intake-status"><span className="status-live" /> Ready to analyze</div></div><div className="format-switcher">{["AUTO", "JSON", "OTLP", "CSV", "LOGS"].map((item) => <button className={format === item ? "active" : ""} key={item} onClick={() => setFormat(item)}>{item}</button>)}</div><textarea id="trace-input" value={trace} onChange={(event) => { setTrace(event.target.value); setError(""); }} placeholder="Paste an OpenTelemetry export, framework trace, log file, or execution event…\n\nWe never store private chain-of-thought. 404 AI uses structured events, state transitions, tool/model metadata, and errors." aria-label="Trace input" /><div className="intake-footer"><div className="intake-file-actions"><button className="upload-trace" onClick={() => inputRef.current?.click()}><CloudUpload size={15} /> Upload trace</button><input ref={inputRef} type="file" accept=".json,.jsonl,.csv,.log,.txt,.ndjson" hidden onChange={(event) => pickFile(event.target.files?.[0])} /><span><FileCode2 size={14} /> Auto-detected · no secrets required</span></div><button className="analyze-trace" onClick={analyze}><Play size={15} fill="currentColor" /> Analyze trace <ArrowRight size={15} /></button></div>{error && <div className="intake-error"><CircleHelp size={14} /> {error}</div>}</section><div className="workspace-divider"><span>or start from a known signal</span></div><section className="starter-section"><div className="starter-heading"><div><span className="workspace-eyebrow">GUIDED INVESTIGATIONS</span><h2>See the method in motion.</h2></div><span>Safe demo traces · no production data</span></div><div className="starter-grid">{starters.map((starter, index) => <button className="starter-card" key={starter.label} onClick={() => { setFormat(index === 0 ? "OTLP" : index === 1 ? "AUTO" : "LOGS"); setTrace(starter.value); setError(""); document.getElementById("trace-input")?.focus(); }}><div className="starter-icon"><UploadCloud size={16} /></div><div><span>{starter.label}</span><strong>{index === 0 ? "OpenTelemetry spans" : index === 1 ? "Agent run metadata" : "Plain-text execution log"}</strong><p>{index === 0 ? "Normalized resource and span events" : index === 1 ? "Framework-agnostic trace payload" : "Human-readable failure sequence"}</p></div><ArrowRight size={15} /></button>)}</div></section><section className="workspace-loop"><div><span className="workspace-eyebrow"><i /> The 404 engineering loop</span><h2>Observe → diagnose → prove → ship.</h2></div><div className="loop-steps"><span>01 Trace</span><span>02 Graph</span><span>03 RCA</span><span>04 Replay</span><span>05 Evaluate</span></div></section>
  </>;
}

export default function WorkspaceHome({ onBack, onAnalyze }: Props) {
  const [activeView, setActiveView] = useState<WorkspaceView>("overview");
  const module = activeView === "agents" ? <AgentRegistry onBackToOverview={() => setActiveView("overview")} /> : activeView === "executions" ? <ExecutionHistory onBackToOverview={() => setActiveView("overview")} /> : activeView === "evaluations" ? <EvaluationWorkspace onBackToOverview={() => setActiveView("overview")} /> : activeView === "rca" ? <PlaceholderModule eyebrow="RCA & evidence" title="Find the decisive step." description="Causal reports, evidence graphs, and recommendations will live here as your saved executions grow." onBack={() => setActiveView("overview")} /> : activeView === "deployments" ? <PlaceholderModule eyebrow="Deployments" title="Ship with confidence." description="Promote evaluated agent versions across sandbox, staging, and production environments." onBack={() => setActiveView("overview")} /> : <Overview onAnalyze={onAnalyze} />;
  return <div className="workspace-shell"><header className="workspace-topbar"><button className="workspace-brand" onClick={onBack}><span>404</span> AI</button><div className="workspace-breadcrumb"><span>Workspace</span><ChevronRight size={13} /><strong>{activeView === "overview" ? "Overview" : activeView}</strong></div><div className="workspace-top-actions"><button className="workspace-icon-button" aria-label="Search"><Search size={16} /></button><button className="workspace-icon-button" aria-label="Help"><CircleHelp size={16} /></button><button className="workspace-user">AM</button></div></header><div className="workspace-body"><aside className="workspace-sidebar"><div className="workspace-switcher"><span className="workspace-mark">W</span><div><b>Acme Research</b><small>Personal workspace</small></div><ChevronRight size={14} /></div><nav className="workspace-nav">{nav.map(([label, view, Icon]) => <button className={activeView === view ? "active" : ""} key={label} onClick={() => setActiveView(view)}><Icon size={16} /><span>{label}</span>{view === "rca" && <em>6</em>}</button>)}</nav><div className="workspace-sidebar-bottom"><button><Settings2 size={16} /> Settings</button><button><TerminalSquare size={16} /> CLI & SDK</button><div className="workspace-upgrade"><span><Sparkles size={14} /> 404 AI platform</span><p>Build, debug, replay and improve every agent.</p><button onClick={() => { setActiveView("overview"); setTimeout(() => document.getElementById("trace-input")?.focus(), 0); }}>Start with a trace <ArrowRight size={13} /></button></div></div></aside><main className="workspace-main">{module}</main></div></div>;
}

function PlaceholderModule({ eyebrow, title, description, onBack }: { eyebrow: string; title: string; description: string; onBack: () => void }) {
  return <div className="placeholder-module"><button className="module-back" onClick={onBack}>← Overview</button><span className="workspace-eyebrow"><i /> {eyebrow}</span><h1>{title}</h1><p>{description}</p><div className="module-empty"><Sparkles size={19} /><p>Connect an agent or analyze an execution to unlock this workspace surface.</p></div></div>;
}
